version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./.nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./.nginx/certbot/www/:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot
    volumes:
      - ./.nginx/certbot/www/:/var/www/certbot/:rw
      - ./.nginx/certbot/etc/:/etc/letsencrypt/:rw