env:
	cp .env.example .env

create-training-data:
	node 1_createData

fine-tune-model:
	node 2_fineTune

web:
	node server

web-chatbot-api:
	node server_chatbot

web-chatbot-line:
	node server_chatbot_line